<?php
/**
 * cat_datos.php — HOFLOC, S.A.
 * ------------------------------
 * Único lugar donde viven los datos del catálogo.
 * Cuando se conecte la BD real, solo se reemplaza
 * este archivo por el fetch de PDO/MySQLi.
 */

$animales = [
    [
        'id'           => 1,
        'nombre'       => 'Genética',
        'tipo'         => 'vaca',
        'raza'         => 'Albera',
        'edad'         => '4 años',
        'peso'         => '500 kg',
        'produccion'   => '20 L / día',
        'num_mida'     => '0F3GHA1',
        'num_finca'    => '88',
        'vacunas'      => 'Al día. Certificado',
        'padre_num'    => '#18867',
        'padre_raza'   => 'Girolando',
        'padre_edad'   => '7 años',
        'padre_peso'   => '560 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#31007',
        'madre_raza'   => 'Holstein',
        'madre_edad'   => '6 años',
        'madre_peso'   => '540 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#10999',
        'cria_raza'    => 'Albera',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Vaca_Alb.jpg',
    ],
    [
        'id'           => 2,
        'nombre'       => 'Genética',
        'tipo'         => 'vaca',
        'raza'         => 'Holstein Roja',
        'edad'         => '5 años',
        'peso'         => '480 kg',
        'produccion'   => '22 L / día',
        'num_mida'     => '0F3GHA2',
        'num_finca'    => '89',
        'vacunas'      => 'Al día. Certificado',
        'padre_num'    => '#18870',
        'padre_raza'   => 'Holstein',
        'padre_edad'   => '8 años',
        'padre_peso'   => '580 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#31010',
        'madre_raza'   => 'Holstein Roja',
        'madre_edad'   => '7 años',
        'madre_peso'   => '520 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#10017',
        'cria_raza'    => 'Holstein Roja',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Vaca_HR.jpg',
    ],
    [
        'id'           => 3,
        'nombre'       => 'Genética',
        'tipo'         => 'toro',
        'raza'         => 'Girolando',
        'edad'         => '6 años',
        'peso'         => '620 kg',
        'produccion'   => '',
        'num_mida'     => '0F3GHA3',
        'num_finca'    => '12',
        'vacunas'      => 'Al día. Certificado',
        'padre_num'    => '#20001',
        'padre_raza'   => 'Gir',
        'padre_edad'   => '9 años',
        'padre_peso'   => '700 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#30002',
        'madre_raza'   => 'Holanda',
        'madre_edad'   => '8 años',
        'madre_peso'   => '510 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#11002',
        'cria_raza'    => 'Girolando',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Toro_Giro.jpg',
    ],
    [
        'id'           => 4,
        'nombre'       => 'Genética',
        'tipo'         => 'toro',
        'raza'         => 'Aberdeen Angus',
        'edad'         => '4 años',
        'peso'         => '650 kg',
        'produccion'   => '',
        'num_mida'     => '0F3GHA4',
        'num_finca'    => '15',
        'vacunas'      => 'Al día. Certificado',
        'padre_num'    => '#20005',
        'padre_raza'   => 'Angus',
        'padre_edad'   => '7 años',
        'padre_peso'   => '720 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#30007',
        'madre_raza'   => 'Angus',
        'madre_edad'   => '6 años',
        'madre_peso'   => '500 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#11005',
        'cria_raza'    => 'Angus',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Toro_Abi.jpg',
    ],
    [
        'id'           => 5,
        'nombre'       => 'Genética',
        'tipo'         => 'ternero',
        'raza'         => 'Brahman',
        'edad'         => '6 meses',
        'peso'         => '120 kg',
        'produccion'   => '',
        'num_mida'     => '0F3GHA5',
        'num_finca'    => '33',
        'vacunas'      => 'Esquema inicial',
        'padre_num'    => '#18880',
        'padre_raza'   => 'Brahman',
        'padre_edad'   => '5 años',
        'padre_peso'   => '600 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#31020',
        'madre_raza'   => 'Brahman',
        'madre_edad'   => '4 años',
        'madre_peso'   => '430 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#10033',
        'cria_raza'    => 'Brahman',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Ternero_Bra.jpg',
    ],
    [
        'id'           => 6,
        'nombre'       => 'Genética',
        'tipo'         => 'ternero',
        'raza'         => 'Holstein',
        'edad'         => '5 meses',
        'peso'         => '110 kg',
        'produccion'   => '',
        'num_mida'     => '0F3GHA6',
        'num_finca'    => '34',
        'vacunas'      => 'Esquema inicial',
        'padre_num'    => '#18881',
        'padre_raza'   => 'Holstein',
        'padre_edad'   => '6 años',
        'padre_peso'   => '590 kg',
        'padre_estado' => 'Activo',
        'madre_num'    => '#31021',
        'madre_raza'   => 'Holstein',
        'madre_edad'   => '5 años',
        'madre_peso'   => '520 kg',
        'madre_estado' => 'Activo',
        'cria_num'     => '#10034',
        'cria_raza'    => 'Holstein',
        'img'          => '../Componentes_Visuales_Animados/img/ImgInicio/Ternero_Hol.jpg',
    ],
];
